---
version: 2.1

orbs:
  release-management: salesforce/npm-release-management@4

jobs:
  lint: &lint
    docker:
      - image: node:latest
    # environment:
    #   - TEST_SERIES: 1
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v5-{{checksum ".circleci/config.yml"}}-{{ checksum "yarn.lock"}}
            - v5-{{checksum ".circleci/config.yml"}}
            - v5
      - run: yarn add -D mocha-junit-reporter@1
      - run: yarn exec nps lint
      - persist_to_workspace: {root: node_modules,  paths: ["*"]}
  compile-typescript:
    <<: *lint
    steps:
      - checkout
      - restore_cache: *restore_cache
      - attach_workspace: {at: node_modules}
      - run: yarn
      - run: rm -rf lib && npx tsc --noEmit && rm -fr lib
  node-latest-multi:
    <<: *lint
    steps: &multi_steps
      - checkout
      - restore_cache: *restore_cache
      - attach_workspace: {at: node_modules}
      - run: .circleci/setup_git
      - run: yarn exec nps test.multi
      - store_test_results: &store_test_results
          path: ~/cli/reports
  node-latest-base:
    <<: *lint
    steps: &base_steps
      - checkout
      - restore_cache: *restore_cache
      - attach_workspace: {at: node_modules}
      - run: .circleci/setup_git
      - run: yarn exec nps test.base
      - store_test_results: *store_test_results
  node-latest-plugin:
    <<: *lint
    steps: &plugin_steps
      - checkout
      - restore_cache: *restore_cache
      - attach_workspace: {at: node_modules}
      - run: .circleci/setup_git
      - run: yarn exec nps test.plugin
      - store_test_results: *store_test_results
  node-latest-single:
    <<: *lint
    steps: &single_steps
      - checkout
      - restore_cache: *restore_cache
      - attach_workspace: {at: node_modules}
      - run: .circleci/setup_git
      - run: yarn exec nps test.single
      - store_test_results: *store_test_results
  node-latest-command:
    <<: *lint
    steps: &command_steps
      - checkout
      - restore_cache: *restore_cache
      - attach_workspace: {at: node_modules}
      - run: .circleci/setup_git
      - run: yarn exec nps test.command
      - store_test_results: *store_test_results
  node-latest-hook:
    <<: *lint
    steps: &hook_steps
      - checkout
      - restore_cache: *restore_cache
      - attach_workspace: {at: node_modules}
      - run: .circleci/setup_git
      - run: yarn exec nps test.hook
      - store_test_results: *store_test_results
  node-16-base: &node_16
    <<: *lint
    docker:
      - image: node:16
    steps: *base_steps
  node-16-plugin:
    <<: *node_16
    steps: *plugin_steps
  node-16-single:
    <<: *node_16
    steps: *single_steps
  node-16-multi:
    <<: *node_16
    steps: *multi_steps
  node-16-command:
    <<: *node_16
    steps: *command_steps
  node-16-hook:
    <<: *node_16
    steps: *hook_steps
  node-14-base: &node_14
    <<: *lint
    docker:
      - image: node:14
    steps: *base_steps
  node-14-plugin:
    <<: *node_14
    steps: *plugin_steps
  node-14-single:
    <<: *node_14
    steps: *single_steps
  node-14-multi:
    <<: *node_14
    steps: *multi_steps
  node-14-command:
    <<: *node_14
    steps: *command_steps
  node-14-hook:
    <<: *node_14
    steps: *hook_steps
  node-12-devcli: &node-12-devcli
    docker:
      - image: oclif/nsis:12.0.0-16
    working_directory: ~/cli
    environment:
      NYC: "yarn exec nyc -- --nycrc-path node_modules/@oclif/nyc-config/.nycrc"
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v6-yarn-{{checksum ".circleci/config.yml"}}-{{ checksum "yarn.lock"}}
            - v6-yarn-{{checksum ".circleci/config.yml"}}
      - run: 'echo "Node: `node --version`"'
      - run: yarn
      - run: .circleci/loadgpg
      - run: yarn add -D nyc@13 @oclif/nyc-config@1
      - run: ./node_modules/.bin/tsc
      - run: ./bin/run --version
      - run: ./bin/run --help

  cache:
    <<: *lint
    steps:
      - checkout
      - restore_cache:
          keys:
            - v5-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
      - run: yarn add -D mocha-junit-reporter@1
      - run: yarn exec nps test.command
      - save_cache:
          key: v5-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
          paths:
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn
workflows:
  version: 2
  oclif:
    jobs:
      - lint
      - compile-typescript
      - node-12-devcli
      - node-latest-base: {requires: [lint, compile-typescript] }
      - node-latest-single: {requires: [lint, compile-typescript] }
      - node-latest-plugin: {requires: [lint, compile-typescript] }
      - node-latest-multi: {requires: [lint, compile-typescript] }
      - node-latest-command: {requires: [lint, compile-typescript] }
      - node-latest-hook: {requires: [lint, compile-typescript] }
      - cache: {requires: [release-management/release-package] }
      - release-management/release-package:
          context: org-global
          github-release: true
          requires:
            - lint
            - compile-typescript
            - node-latest-base
            - node-latest-single
            - node-latest-plugin
            - node-latest-multi
            - node-latest-command
            - node-latest-hook
          filters:
            branches:
              only: master
  nightly:
    triggers:
      - schedule:
          cron: "0 11 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - lint
      - compile-typescript
      - node-12-devcli
      - node-latest-base: {requires: [lint, compile-typescript] }
      - node-latest-single: {requires: [lint, compile-typescript] }
      - node-latest-plugin: {requires: [lint, compile-typescript] }
      - node-latest-multi: {requires: [lint, compile-typescript] }
      - node-latest-command: {requires: [lint, compile-typescript] }
      - node-latest-hook: {requires: [lint, compile-typescript] }
      - node-16-base: {requires: [lint, compile-typescript] }
      - node-16-single: {requires: [lint, compile-typescript] }
      - node-16-plugin: {requires: [lint, compile-typescript] }
      - node-16-multi: {requires: [lint, compile-typescript] }
      - node-16-command: {requires: [lint, compile-typescript] }
      - node-16-hook: {requires: [lint, compile-typescript] }
      - node-14-base: {requires: [lint, compile-typescript] }
      - node-14-single: {requires: [lint, compile-typescript] }
      - node-14-plugin: {requires: [lint, compile-typescript] }
      - node-14-multi: {requires: [lint, compile-typescript] }
      - node-14-command: {requires: [lint, compile-typescript] }
      - node-14-hook: {requires: [lint, compile-typescript] }
