# test
name: version, tag and github release

on:
  push:
    branches:
      - main
      - prerelease/**
    tags-ignore:
      - "*"

jobs:
  release:
    uses: salesforcecli/github-workflows/.github/workflows/githubRelease.yml@secrets-input
    secrets:
      SVC_CLI_BOT_GITHUB_TOKEN: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}
    with:
      prerelease: ${{ github.ref_name != 'main' }}
  # most repos won't use this
  # depends on previous job to avoid git collisions, not for any functionality reason
  # docs:
  #   uses: salesforcecli/github-workflows/.github/workflows/publishTypedoc.yml@main
  #   secrets: inherit
  #   needs: release
