# test
name: version, tag and github release

on:
  push:
    branches:
      - main
      - prerelease/**
    tags-ignore:
      - "*"

jobs:
  release:
    uses: salesforcecli/github-workflows/.github/workflows/githubRelease.yml@secrets-input
    secrets:
      SVC_CLI_BOT_GITHUB_TOKEN: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}
    with:
      prerelease: ${{ github.ref_name != 'main' }}
