on:
  push:
    branches:
      - main
      # point at specific branches, or a naming convention via wildcard
      - prerelease/*
    tags-ignore:
      - "*"

jobs:
  release:
    # this job will throw if prerelease is true but it doesn't have a prerelease-looking package.json version
    uses: oclif/github-workflows/.github/workflows/githubRelease.yml@main
    secrets: inherit
    with:
      prerelease: ${{ github.ref_name != 'main' }}
